### ISSUE TITLE
how could we apply max acceleration and max Velocity and max and min joint angle bound to the gspline

### ISSUE THREAD

**Issue by dbdxnuliba** [rafaelrojasmiliani/gsplines_cpp#52]
how could we apply max acceleration and max Velocity and max and min joint angle bound to the gspline

**Comment by rafaelrojasmiliani** [comment]
You can linearly scale the trajectory.   Use [`Gspline::linear_scaling_new_execution_time`](https://github.com/rafaelrojasmiliani/gsplines_cpp/blob/8a52e02c3924e429a3875a662a901ab78b2d50b4/include/gsplines/GSpline.hpp#L205) to get a new `Gspline` with a new execution time compued as $T_{\text{new}}= \frac{\max_t \dot q(t)}{V_{\text{max}}} T_{\text{old}}$ of the velocity, $T_{\text{new}}= \srqt{\frac{\max_t \ddot q(t)}{A_{\text{max}}}} T_{\text{old}}$ for the acceleration, etc.

**Comment by rafaelrojasmiliani** [comment]
You can also see [here](https://github.com/rafaelrojasmiliani/gsplines_cpp_ros/blob/155d756f91d1dd2a8f4ea80c436f83d8541e8e15/gsplines_ros/src/gsplines_ros.cpp#L306) how a gspline can be scaled in order to have minimize its execution time given upper velocity and acceleration limits
